// Offline catalogue used to (a) populate the central DB on first boot with the
// "most popular games of the moment" and (b) act as an IGDB fallback so the app
// is fully functional even without Twitch/IGDB credentials configured.
// Each record matches the metadata the spec requires us to store.

export const POPULAR_GAMES = [
  {
    igdb_id: 119133, titolo: 'Elden Ring', publisher: 'FromSoftware',
    data_pubblicazione: '2022-02-25', genere: 'Action RPG',
    descrizione: 'Il Senzaluce si alza e viene guidato dalla grazia per rivendicare l\'Anello Ancestrale e diventare Lord Ancestrale nell\'Interregno.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg',
    saga: 'Souls', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1245620' }, { store: 'epic', name: 'Epic Games', url: 'https://store.epicgames.com/p/elden-ring' }],
    lingue: ['Italiano', 'English', 'Français', '日本語'], tags: ['Soulslike', 'Open World', 'Dark Fantasy'],
    piattaforme: ['PC', 'PS5', 'PS4', 'Xbox Series', 'Xbox One'], time_to_beat: 58, rating: 96, steam_appid: 1245620, popularity: 100,
  },
  {
    igdb_id: 26226, titolo: 'Hollow Knight', publisher: 'Team Cherry',
    data_pubblicazione: '2017-02-24', genere: 'Metroidvania',
    descrizione: 'Esplora un vasto regno sotterraneo in rovina in questa avventura metroidvania disegnata a mano.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rgi.jpg',
    saga: 'Hollow Knight', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/367520' }],
    lingue: ['Italiano', 'English'], tags: ['Metroidvania', 'Difficile', 'Indie'],
    piattaforme: ['PC', 'Switch', 'PS4', 'Xbox One'], time_to_beat: 27, rating: 90, steam_appid: 367520, popularity: 88,
  },
  {
    igdb_id: 119388, titolo: 'The Legend of Zelda: Tears of the Kingdom', publisher: 'Nintendo',
    data_pubblicazione: '2023-05-12', genere: 'Action-Adventure',
    descrizione: 'Un\'epica avventura attraverso le terre e i cieli di Hyrule.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5vmg.jpg',
    saga: 'The Legend of Zelda', store_links: [{ store: 'nintendo', name: 'Nintendo eShop', url: 'https://www.nintendo.com' }],
    lingue: ['Italiano', 'English', '日本語'], tags: ['Open World', 'Avventura'],
    piattaforme: ['Switch'], time_to_beat: 60, rating: 96, popularity: 95,
  },
  {
    igdb_id: 115540, titolo: 'Mario Kart 8 Deluxe', publisher: 'Nintendo',
    data_pubblicazione: '2017-04-28', genere: 'Racing',
    descrizione: 'Il kart racing definitivo torna su Nintendo Switch con tracciati e personaggi.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co213j.jpg',
    saga: 'Mario', store_links: [{ store: 'nintendo', name: 'Nintendo eShop', url: 'https://www.nintendo.com' }],
    lingue: ['Italiano', 'English'], tags: ['Racing', 'Multiplayer', 'Family'],
    piattaforme: ['Switch'], time_to_beat: 20, rating: 92, popularity: 80,
  },
  {
    igdb_id: 134101, titolo: 'Final Fantasy XVI', publisher: 'Square Enix',
    data_pubblicazione: '2023-06-22', genere: 'Action RPG',
    descrizione: 'Un dark fantasy epico ambientato nel regno di Valisthea.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5w6q.jpg',
    saga: 'Final Fantasy', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/2515020' }],
    lingue: ['Italiano', 'English', '日本語'], tags: ['JRPG', 'Dark Fantasy'],
    piattaforme: ['PC', 'PS5'], time_to_beat: 35, rating: 87, steam_appid: 2515020, popularity: 78,
  },
  {
    igdb_id: 25076, titolo: 'Red Dead Redemption 2', publisher: 'Rockstar Games',
    data_pubblicazione: '2018-10-26', genere: 'Action-Adventure',
    descrizione: 'L\'epopea di Arthur Morgan e della banda Van der Linde nell\'America del 1899.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg',
    saga: 'Red Dead', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1174180' }, { store: 'epic', name: 'Epic Games', url: 'https://store.epicgames.com' }],
    lingue: ['Italiano', 'English'], tags: ['Open World', 'Western', 'Story Rich'],
    piattaforme: ['PC', 'PS4', 'Xbox One'], time_to_beat: 50, rating: 97, steam_appid: 1174180, popularity: 90,
  },
  {
    igdb_id: 113112, titolo: 'Hades', publisher: 'Supergiant Games',
    data_pubblicazione: '2020-09-17', genere: 'Roguelike',
    descrizione: 'Sfida il dio dei morti mentre fuggi dagli inferi in questo roguelike d\'azione.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co39vc.jpg',
    saga: 'Hades', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1145360' }],
    lingue: ['Italiano', 'English'], tags: ['Roguelike', 'Indie', 'Action'],
    piattaforme: ['PC', 'Switch', 'PS5', 'Xbox Series'], time_to_beat: 22, rating: 93, steam_appid: 1145360, popularity: 82,
  },
  {
    igdb_id: 1877, titolo: 'Cyberpunk 2077', publisher: 'CD Projekt Red',
    data_pubblicazione: '2020-12-10', genere: 'Action RPG',
    descrizione: 'Un\'avventura open-world a Night City, megalopoli ossessionata dal potere e dalla modificazione corporea.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7497.jpg',
    saga: 'Cyberpunk', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1091500' }, { store: 'epic', name: 'Epic Games', url: 'https://store.epicgames.com' }, { store: 'gog', name: 'GOG', url: 'https://www.gog.com' }],
    lingue: ['Italiano', 'English'], tags: ['Open World', 'Cyberpunk', 'RPG'],
    piattaforme: ['PC', 'PS5', 'Xbox Series'], time_to_beat: 25, rating: 86, steam_appid: 1091500, popularity: 85,
  },
  {
    igdb_id: 217590, titolo: 'Marvel\'s Spider-Man 2', publisher: 'Insomniac Games',
    data_pubblicazione: '2023-10-20', genere: 'Action-Adventure',
    descrizione: 'Peter Parker e Miles Morales affrontano nuove minacce a New York.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6mz2.jpg',
    saga: 'Marvel\'s Spider-Man', store_links: [{ store: 'playstation', name: 'PS Store', url: 'https://store.playstation.com' }],
    lingue: ['Italiano', 'English'], tags: ['Supereroi', 'Open World'],
    piattaforme: ['PS5'], time_to_beat: 18, rating: 90, popularity: 79,
  },
  {
    igdb_id: 144020, titolo: 'God of War Ragnarök', publisher: 'Santa Monica Studio',
    data_pubblicazione: '2022-11-09', genere: 'Action-Adventure',
    descrizione: 'Kratos e Atreus affrontano il Ragnarök incombente nei Nove Regni.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5v.jpg',
    saga: 'God of War', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/2322010' }, { store: 'playstation', name: 'PS Store', url: 'https://store.playstation.com' }],
    lingue: ['Italiano', 'English'], tags: ['Mitologia', 'Story Rich'],
    piattaforme: ['PC', 'PS5', 'PS4'], time_to_beat: 26, rating: 94, steam_appid: 2322010, popularity: 87,
  },
  {
    igdb_id: 119171, titolo: 'Baldur\'s Gate 3', publisher: 'Larian Studios',
    data_pubblicazione: '2023-08-03', genere: 'CRPG',
    descrizione: 'Un GDR basato su Dungeons & Dragons con scelte e conseguenze profonde.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co670h.jpg',
    saga: 'Baldur\'s Gate', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1086940' }, { store: 'gog', name: 'GOG', url: 'https://www.gog.com' }],
    lingue: ['Italiano', 'English'], tags: ['CRPG', 'Turn-Based', 'Co-op'],
    piattaforme: ['PC', 'PS5', 'Xbox Series'], time_to_beat: 75, rating: 96, steam_appid: 1086940, popularity: 93,
  },
  {
    igdb_id: 144879, titolo: 'The Last of Us Part I', publisher: 'Naughty Dog',
    data_pubblicazione: '2022-09-02', genere: 'Action-Adventure',
    descrizione: 'Il remake della storia di Joel ed Ellie in un\'America post-pandemica.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5ziw.jpg',
    saga: 'The Last of Us', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1888930' }, { store: 'playstation', name: 'PS Store', url: 'https://store.playstation.com' }],
    lingue: ['Italiano', 'English'], tags: ['Story Rich', 'Survival'],
    piattaforme: ['PC', 'PS5'], time_to_beat: 15, rating: 88, steam_appid: 1888930, popularity: 84,
  },
  {
    igdb_id: 200001, titolo: 'Grand Theft Auto VI', publisher: 'Rockstar Games',
    data_pubblicazione: '2026-05-22', genere: 'Action-Adventure',
    descrizione: 'Il prossimo capitolo della saga GTA, ambientato a Vice City.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co8b8a.jpg',
    saga: 'Grand Theft Auto', store_links: [{ store: 'rockstar', name: 'Rockstar', url: 'https://www.rockstargames.com' }],
    lingue: ['Italiano', 'English'], tags: ['Open World', 'Crime'],
    piattaforme: ['PS5', 'Xbox Series'], time_to_beat: 40, rating: null, popularity: 99,
  },
  {
    igdb_id: 7350, titolo: 'DOOM Eternal', publisher: 'id Software',
    data_pubblicazione: '2020-03-20', genere: 'FPS',
    descrizione: 'Lo Slayer torna per spazzare via le orde demoniache sulla Terra.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co22nk.jpg',
    saga: 'DOOM', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/782330' }],
    lingue: ['Italiano', 'English'], tags: ['FPS', 'Fast-Paced', 'Action'],
    piattaforme: ['PC', 'PS4', 'Xbox One', 'Switch'], time_to_beat: 14, rating: 88, steam_appid: 782330, popularity: 70,
  },
  {
    igdb_id: 198214, titolo: 'Lies of P', publisher: 'Neowiz',
    data_pubblicazione: '2023-09-19', genere: 'Action RPG',
    descrizione: 'Un soulslike dark che reinterpreta la fiaba di Pinocchio nella città di Krat.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6f1q.jpg',
    saga: 'Lies of P', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1627720' }],
    lingue: ['Italiano', 'English'], tags: ['Soulslike', 'Dark Fantasy'],
    piattaforme: ['PC', 'PS5', 'Xbox Series'], time_to_beat: 30, rating: 81, steam_appid: 1627720, popularity: 68,
  },
  {
    igdb_id: 17000, titolo: 'Starfield', publisher: 'Bethesda Game Studios',
    data_pubblicazione: '2023-09-06', genere: 'Action RPG',
    descrizione: 'Esplora la galassia in questo GDR spaziale open-world.',
    copertina_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6ij3.jpg',
    saga: 'Starfield', store_links: [{ store: 'steam', name: 'Steam', url: 'https://store.steampowered.com/app/1716740' }, { store: 'microsoft', name: 'Microsoft Store', url: 'https://www.xbox.com' }],
    lingue: ['Italiano', 'English'], tags: ['Space', 'Open World', 'RPG'],
    piattaforme: ['PC', 'Xbox Series'], time_to_beat: 45, rating: 83, steam_appid: 1716740, popularity: 72,
  },
];
